"""product table commit

Revision ID: 1d5d26edf789
Revises: 8a9066b81875
Create Date: 2026-05-19 15:12:15.383527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5d26edf789'
down_revision: Union[str, Sequence[str], None] = '8a9066b81875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_Id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('prod_Id', sa.VARCHAR(), nullable=True),
    sa.Column('prod_name', sa.VARCHAR(), nullable=True),
    sa.Column('prod_cost', sa.VARCHAR(), nullable=True),
    sa.Column('prod_disc', sa.VARCHAR(), nullable=True),
    sa.Column('prod_count', sa.VARCHAR(), nullable=True),
    sa.Column('prod_status', sa.VARCHAR(), nullable=True),
    sa.Column('prod_added_at', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_products_Id'), 'products', ['Id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('create_data', sa.DATE(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
